#!/bin/bash

#case-menu: a menu driven system information program

clear
echo "
Please Select:
1. Display System information
2. Display Disk Space
3. Display Home Space Utilization
0. Quit
"

read -p "Enter selection [0-3] > "
case $REPLY in
  0) echo "program terminated"
     exit
     ;;
  1) echo "Hostname: $HOSTNAME"
     uptime
     ;;
  2) df -h
     ;;
  3) if [[ $(id -u) -eq 0 ]]; then
      echo "Home Space Utilisation (All Users)"
      du -sh /home/*
     else
      echo "Home Space Utilisation ($USER)"
      du -sh $Home
     fi
     ;;
  *) echo "Invalid entry" >&2
     exit 1
     ;;
esac
