#!/bin/bash

read -p "Enter word > "
case $REPLY in
  [[:alpha:]])  echo "is a single alphabetic character.";;
  [ABC][0-9])   echo " is A, B, or C followed by digit.";;
  ???)          echo " is three characters long. ";;
  *.txt)        echo "is word ending in '.txt' ";;
  *)            echo " is something else.";;
esac
