#!/bin/bash
# Program to output a system information page

title="System Information Report for $HOSTNAME"

echo "<HTML>
	<HEAD>
		<TITLE>$title</title>
	<HEAD>
	  <BODY>
		<H1>$title</H1>
		<H2>$HOSTNAME</H2>
	<BODY>
	<HTML>"
